language: shell
os: linux
dist: xential

services:
  - docker

before_install:
  - pip install --user -r requirements.txt
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

install:
  - invoke build
  - docker images

script:
  - invoke export
  - invoke extract
  - invoke images
  - invoke download
  - du -h *.img *.tar
