language: minimal
sudo: required

services:
  - docker

before_install:
  - pip install --user invoke
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker images

install:
  - invoke build
  - docker images

script:
  - invoke export
  - invoke extract
  - invoke images
  - invoke download
  - du -h {boot,root,home}.img
