language: minimal
sudo: required

services:
  - docker

before_install:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - docker images

install:
  - docker build --no-cache --build-arg user_login=slach -t slach/archstrap .

script:
  - docker images
  - docker run -it -d --rm --name archstrap slach/archstrap
  - docker export archstrap > archstrap.tar
  - docker stop archstrap
  - tar tvf archstrap.tar | wc -l
  - du -sh archstrap.tar
