language: shell
os: linux
dist: xenial

services:
  - docker

before_install:
  - apt update -y
  - apt install --only-upgrade docker-ce -y
  - docker version
  - pip install --user -r requirements.txt
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

install:
  - invoke build
  - docker images

script:
  - invoke export
  - invoke extract
  - invoke images
  - invoke download
  - du -h *.img *.tar *.ext4
  - docker run -it --rm slach/archstrap ls -la /
