language: python
sudo: required

services:
  - docker

before_install:
  - docker images

install:
  - docker build --no-cache -t slach/archstrap .

script:
  - docker images
  - docker run -it -d --rm --name archstrap slach/archstrap
  - docker export archstrap > archstrap.tar
  - docker stop archstrap
  - tar tvf archstrap.tar
  - du -sh archstrap.tar
