language: shell
os: linux
dist: bionic

services:
  - docker

before_install:
  - pip install --user -r requirements.txt
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

install:
  - invoke build
  - docker images

script:
  - invoke export
  - invoke extract
  - ls -lh *.tar
  - invoke images
  - invoke download
  - touch disk.img
  - dd if=boot.img of=disk.img bs=1M oflag=append conv=notrunc
  - dd if=root.img of=disk.img bs=1M oflag=append conv=notrunc
  - dd if=home.img of=disk.img bs=1M oflag=append conv=notrunc
  - ls -lh *.img
  - gzip archstrap.img
  - docker run -d -it --rm --name artifacts alpine
  - docker cp archstrap.img.gz artifacts:/archstrap.img.gz
  - docker stop
  - docker tag artifacts littlelover/archstrap
  - docker push littlelover/archstrap
