language: shell
os: linux
dist: bionic

services:
  - docker

before_install:
  - pip install --user -r requirements.txt
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

install:
  - invoke build
  - docker images

script:
  - invoke export
  - invoke extract
  - ls -lh *.tar
  - rm -rf *.tar
  - invoke images
  - invoke download
  - ls -lh *.img
  - cat boot.img root.img home.img >> archstrap.img
  - ls -lh archstrap.img
