language: shell
os: linux
dist: xenial

services:
  - docker

before_install:
  - pip install --user -r requirements.txt
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

install:
  - invoke build
  - docker images

script:
  - invoke export
  - invoke extract
  # - invoke images
  # - invoke download
  - du -h *.img *.tar *.ext4
  - docker save slach/archstrap > rootfs.tar
  - tar -tvf rootfs.tar
