language: python
sudo: required

services:
  - docker

before_install:
  - docker images

install:
  - docker build -t slach/archbootrapper .

script:
  - docker images
  - docker run -it -d --rm --name archstrapper slach/archstrapper
  - docker export archstrapper > archstrapper.tar
  - docker stop archstrapper
  - tar tvf archstrapper.tar
  - du -sh archstrapper.tar
